package da.codes;

//--v-david---1396-01-30--

public class ExceptionMessageCode {
    public static final String GENERAL_NATIONALITY_LOCATION_SHOULD_BE_COUNTRY = "GENERAL_NATIONALITY_LOCATION_SHOULD_BE_COUNTRY";
    public static final String GENERAL_BIRTH_LOCATION_SHOULD_BE_CITY = "GENERAL_BIRTH_LOCATION_SHOULD_BE_CITY";
    public static final String GENERAL_REGISTER_LOCATION_SHOULD_BE_CITY = "GENERAL_REGISTER_LOCATION_SHOULD_BE_CITY";
    public static final String GENERAL_NOT_THE_METHOD_NAME = "GENERAL_NOT_THE_METHOD_NAME";

    public static final String GENERAL_VALUE_OF_VARIABLE_CATEGORY_ELEMENT_IS_DUPLICATED = "GENERAL_VALUE_OF_VARIABLE_CATEGORY_ELEMENT_IS_DUPLICATED";
    public static final String GENERAL_VALUE_OF_ENTITY_IS_DUPLICATED = "GENERAL_VALUE_OF_ENTITY_IS_DUPLICATED";
    public static final String GENERAL_LIST_IS_EMPTY = "GENERAL_LIST_IS_EMPTY";
    public static final String GENERAL_LIST_IS_EMPTY_OR_NOT_CORRECT = "GENERAL_LIST_IS_EMPTY_OR_NOT_CORRECT";
    public static final String GENERAL_VALUE_OF_LIST_IS_EMPTY = "GENERAL_VALUE_OF_LIST_IS_EMPTY";
    public static final String GENERAL_VALUE_IS_NO_TEXT = "GENERAL_VALUE_IS_NO_TEXT";
    public static final String GENERAL_VALUE_IS_NO_NUMBER = "GENERAL_VALUE_IS_NO_NUMBER";
    public static final String GENERAL_VALUE_IS_NO_BOOLEAN = "GENERAL_VALUE_IS_NO_BOOLEAN";
    public static final String GENERAL_VALUE_IS_FALSE = "GENERAL_VALUE_IS_FALSE";
    public static final String GENERAL_VALUE_IS_MAX = "GENERAL_VALUE_IS_MAX";
    public static final String GENERAL_VALUE_IS_MIN = "GENERAL_VALUE_IS_MIN";
    public static final String GENERAL_VALUE_IS_NOT_EQUAL = "GENERAL_VALUE_IS_NOT_EQUAL";
    public static final String GENERAL_VALUE_IS_EQUAL = "GENERAL_VALUE_IS_EQUAL";
    public static final String GENERAL_VALUE_IS_NOT_GREATER_THAN_OR_EQUAL = "GENERAL_VALUE_IS_NOT_GREATER_THAN_OR_EQUAL";
    public static final String GENERAL_VALUE_IS_NOT_LESS_THAN_OR_EQUAL = "GENERAL_VALUE_IS_NOT_LESS_THAN_OR_EQUAL";
    public static final String GENERAL_VALUE_IS_NOT_GREATER_THAN = "GENERAL_VALUE_IS_NOT_GREATER_THAN";
    public static final String GENERAL_VALUE_IS_NOT_LESS_THAN = "GENERAL_VALUE_IS_NOT_LESS_THAN";
    public static final String GENERAL_COLLECTION_DUPLICATED_ROW = "GENERAL_COLLECTION_DUPLICATED_ROW";
    public static final String GENERAL_ENTITY_IS_NULL = "GENERAL_ENTITY_IS_NULL";
    public static final String GENERAL_VALUE_IS_NULL = "GENERAL_VALUE_IS_NULL";
    public static final String GENERAL_VALUE_IS_NOT_NULL = "GENERAL_VALUE_IS_NOT_NULL";
    public static final String GENERAL_GET_VALUE = "GENERAL_GET_VALUE";
    public static final String GENERAL_LIST_IS_NULL = "GENERAL_LIST_IS_NULL";
    public static final String GENERAL_LIST_VALUE_IS_NULL = "GENERAL_LIST_VALUE_IS_NULL";
    public static final String GENERAL_DEFINE = "GENERAL_DEFINE";
    public static final String GENERAL_EDIT = "GENERAL_EDIT";
    public static final String GENERAL_LOAD = "GENERAL_LOAD";

}
//--^-david---1396-01-30--

